### ISSUE TITLE
Can you please document this at least a tiny bit

### ISSUE THREAD

**Issue by Gozala** [atom/teletype-crdt#14]
## Summary

I'm working on p2p collaborative rich text editor. I've started with https://quilljs.com/ for editor component and [Automerge JSON CRDTs](https://github.com/automerge/automerge) library that uses RGA algorithm for text.

However I find RGA to be problematic with a rich text because data model consists of marked text fragments which fairly often get split and that corresponds to deleting one part of the marked fragment and then reinserting which breaks causality (for changes of the part of the fragment that got deleted and then reinserted).

## Motivation

I'm inclined to think that RGASplit (which I believe what this library is based on) might provide a solution for the outlined problem. Unfortunately lack of documentation makes it really hard to asses viability or even get started with this library.

## Describe alternatives you've considered

Trying to figure out the API by reading the source code.

**Comment by rsese** [comment]
Thanks for the feedback :+1:

With the work on the team's plate across Atom at the moment, adding this documentation isn't something we'd be able to prioritize in the near future unfortunately.   Since we try use our issues list to track tasks to be completed, we're going to close this out for now but can reopen if it's something that someone will take on.
